### ISSUE TITLE
Form name `tags` not added to Kobo Message body

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#22]
When I run the `historical.js` job, it fetches Kobo data, adds a `tag`, and posts the data back to OpenFn inbox.
https://github.com/OpenFn/wcs/blob/aba35c705b14550cff243ff1d1c5ee8bff393563/bns/historical.js#L35

[See output here](https://www.openfn.org/projects/1168/messages/9092195). The form name `tag` is not being added, so this message therefore doesn't trigger the next jobs. To replicate, run [this `historical.js` job.](https://www.openfn.org/projects/1168/jobs/3542) 

Please make any updates in both the `historical.js` and `getKoboData.js` jobs (these are effectively the same jobs, just with different formIds and trigger configurations). Ty!

**Comment by taylordowns2000** [comment]
seemed to be a last-job-state issue... maybe because we had changed this job significantly and hadn't cleared state. seems OK now, but let's watch.
