### ISSUE TITLE
Delete either bns/historical.js or bns/getKoboData.js

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#23]
@aleksa-krolls , can I delete one of these jobs? They're almost identical. If there's some reason we currently have both, maybe we could accommodate that in state?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 No, please do not delete. They serve different purposes even though they're effectively the same job. They will have different form Ids and 1 will be configured in OpenFn to run on an ongoing basis, while the other is used for once-off, ad hoc migration. Happy to explore better ways to achieve this if you have ideas --> but with 2 different triggers and 2 different Ids, makes it easy to keep as 2 jobs. See the docs for more info: https://github.com/OpenFn/wcs
