### ISSUE TITLE
BNS and NRGT jobs time out on production

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#24]
## Issue
When running the `historical.js` on OpenFn.org WCS project, all the jobs time out after 100s ([see run here](https://www.openfn.org/projects/1168/runs/9867364)). 

When run, this job should fetch historical submissions for the ~20 Kobo forms listed in the job. It should then post each individual submission back to the OpenFn inbox, which will trigger the appropriate job (i.e., `bns/survey.js`, `nrgt/2017.js`) to run and process the individual Kobo submissions to the connect mssql db. 

## Steps to replicate
Run this job: https://www.openfn.org/projects/1168/jobs/3542

I recommend testing locally to see run-time before running again on prod. 

## state.json
See LP for creds (WCS Kobo Toolbox - BNS)

## adaptor
language-mssqql

## output
See the readme for info on how this should work.

**Comment by taylordowns2000** [comment]
There's a `1000ms` delay built in to _each_ post… we've got 10k submissions, and 10,000 is longer than 100 seconds, so we time out. This was all me, building some throttling into the job that this one was _based on_, and not realising how this would be used in the wild. If we want to preserve a single post _per_ form, we might need to split this up somehow. If we can bulkify the other jobs, we could likely do all 10k in 100 seconds.

**Comment by taylordowns2000** [comment]
At present, it takes ~2 minutes to fetch `10406` submissions from `46` different forms. If WCS wants individual transactions on OpenFn for each submission on Kobo, we can't batch the subsequent posts to their inbox. Attempting to make all 10k post requests (with 1,731,000 lines of JSON) to OpenFn simultaneously seems wrong from a resource consumption perspective. I see two ways forward:

1. Allow the job to run for longer than 100 seconds and keep some small throttling (of 200-400ms, maybe?) between posts?
2. Ask WCS if they're OK with historical loads happening in bulk. If they are, we'd then need to refactor `bns/survey.js` (and related jobs) to handle either a single submission or an array of submissions. We'd then make 42 posts to OpenFn, and see 42 subsequent postgres jobs run, loading 10k submissions in total.

I'm open to any other ideas, and want to discuss this with you, @lakhassane and @aleksa-krolls , today.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 As discussed, please run the jobs for the 42 forms locally (this is expected to be a one-time bulk migration). That said, the client wants to understand the limits of the current job to flag when they might need support with future historical migrations. From WCS: 
- if we had a single form, what number of submissions in any run will block the integration?
- Does the number of forms also add to the issue? By how much?

Any way to do some quick testing to determine rough bounds of the current solution so that we can say something like any migration involving more then X Kobo surveys and Y forms might require this job to be run locally?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Another scenario to consider here... what if there are 42 Kobo forms, but only <10 submissions each?

**Comment by taylordowns2000** [comment]
Increased estimate from 3-5

**Comment by taylordowns2000** [comment]
1. Running locally now (almost done)
2. After local run complete, will need to analyze errors (about 99% going thru w/o error) cluster them, and _may_ make changes to the jobs or need to ask WCS to inform changes to the jobs or db.
3. reprocessed failed data
------------------------------------
4. analyze timing for bulk run and provide WCS with incications of how many thousands of submissions they can expect to process on OpenFn.org, vs. when they'd need to run it from a command line.

**Comment by taylordowns2000** [comment]
Closing as I've tested this on production. The timeouts are fixed, but "normal" mapping errors or db change requests may still be remaining. see issue #26
