### ISSUE TITLE
Analyze Kobo bug with duplicates & WCS job impacts

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#31]
See this bug here: https://community.kobotoolbox.org/t/submissions-being-duplicated-with-same-uuid/12503/8

Question: Does this impact any of our existing WCS jobs? (I hope no, because we are always upserting records... but can you please analyze to confirm?)

**Comment by lakhassane** [comment]
@aleksa-krolls I have been reading the issue and still can't see no impact. Given we are using `upsert` based on a specific `uuid` the conditions on the `language-package` would not allow duplications to be made.

**Comment by aleksa-krolls** [comment]
@lakhassane great news. consider resolved then :)
