### ISSUE TITLE
Error converting data type varchar to numeric on bns/survey.js

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#40]
Message: https://openfn.org/projects/1168/messages/9538015
Run: https://openfn.org/projects/1168/runs/9952883

```
Executing upsert via : MERGE WCSPROGRAMS_KoboBnsAnswergps AS [Target]
        USING (SELECT '12406856' AS AnswerId, '2018-07-13T07:30:56-aEypYtcfNGvDtpkSUPXrJN-12406856' AS DatasetUuidId, ',' AS Geom, '12406856' AS Id, '2018-07-13T07:30:56' AS LastUpdate, '6.955409726059E12' AS Lat, NULL AS Long) AS [Source] 
        ON [Target].AnswerId = [Source].AnswerId
        WHEN MATCHED THEN
          UPDATE SET [Target].AnswerId='12406856', [Target].DatasetUuidId='2018-07-13T07:30:56-aEypYtcfNGvDtpkSUPXrJN-12406856', [Target].Geom=',', [Target].Id='12406856', [Target].LastUpdate='2018-07-13T07:30:56', [Target].Lat='6.955409726059E12', [Target].Long=NULL 
        WHEN NOT MATCHED THEN
          INSERT (AnswerId, DatasetUuidId, Geom, Id, LastUpdate, Lat, Long) VALUES ([Source].AnswerId, [Source].DatasetUuidId, [Source].Geom, [Source].Id, [Source].LastUpdate, [Source].Lat, [Source].Long);
Error converting data type varchar to numeric.
```

**Comment by taylordowns2000** [comment]
![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/67279e0c-8eca-4eec-a0b8-72b7c75ee59a)

**Comment by lakhassane** [comment]
@aleksa-krolls What is the need around the `lat` and `long` data. From a value perspective the values seem wrong. 
`"gps/lat": "6.955409726059E12"` => lat = 6955409726059.0 which does not seem to be a correct value.

1. If they should be stored as is we can make a DB change.
2. Otherwise we can make a processing on the value returned but on what basis?

The concerned table is `WCSPROGRAMS_KoboBnsAnswergps`

**Comment by taylordowns2000** [comment]
Will wait for @aleksa-krolls and Jonathan to comment on this, but could the `E` mean east? As in "6.9 degrees East"? Either way, it smells like user error and improper field validation in Kobo.

When I analyse the other messages (type `{"body":{"gps_method":"manual"}}` into the filter on their inbox) with manual gps data I see data like this:
- https://openfn.org/projects/1168/messages/9539660
- https://openfn.org/projects/1168/messages/9539653

It's all proper floats. Maybe this was just one bad submission in Kobo?

**Comment by aleksa-krolls** [comment]
@lakhassane so sometimes they collect gps manually. This `6.955409726059E12` example was a user data entry error, so this message should fail... they put the 2 values (lat and long) in the same field (lat). WCS has now corrected the value in Kobo, so I am able to run the message successfully: https://openfn.org/projects/1168/runs/9955450

How much effort would it be to add a custom error message for the GPS fields? If ~5 minutes to implement, could we throw an error that the GPS has been incorrectly entered if a GPS value as an alpha character like `E` in it again? 
If it will take longer, please disregard :)

**Comment by taylordowns2000** [comment]
less than 5. i'm doing it now
