### ISSUE TITLE
handle repeat groups

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#41]
Hey @lakhassane , I've got the job working as intended, but I'm not sold on the intent! We discussed this briefly on our call, but how repeat groups are set up is not scalable. In my mind, the logic that must be implemented is:

1. figure out how many repeat groups are in a form, if any
2. for `each` repeat group plus the parent itself, push a new "table" object into the `tablesToBeCreated` array

The table object has two keys, as far as I can tell:
```js
{ name: table_name, columns: [ { name: 'animal_code', type: 'varchar' }, ... ] },
```

**Comment by lakhassane** [comment]
@taylordowns2000 I added a commit here about what we did in `01-getForm.js`
