### ISSUE TITLE
Altered Kobo surveys must create Postgres tables and configure the OpenFn platform

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#43]
# WCS Postgres Table Management Jobs

## Background

WCS collects research data across several sites and surveys, which are managed by a number of staff. To ensure that all Kobo survey data can be securely and centrally captured for easier access and analysis, WCS would like to automate the process of integrating Kobo surveys and creating database tables to centrally store the data. 

- As a WCS researcher, I would like to upload a new Kobo survey and have a corresponding Postgres destination table and integration mapping automatically created, so that my survey data will sync with the database automatically with no additional effort on my side. 
- As a WCS researcher, I would like all Kobo surveys of the same type to map to the same destination database table, so that I can collect data across multiple sites and Kobo forms, but view the data in one centralized table. 
- As a WCS researcher, I would like the option to add new questions to my Kobo surveys and have that automatically add a corresponding column in the destination database, so that any new survey questions will automatically map to the database with no additional effort on my side. 

## The specific request

Goal is to identify an automated or semi-automated process for going from a new or updated Kobo form to a Postgres set of holding tables. This will require an automated metadata _and_ data sync between Kobo Toolbox and Postgresql.

## state.json
**Source: Kobo** 
- Use this [WCS Rural Consumption Test ](https://kf.kobotoolbox.org/#/forms/afCPRfan8JdBt9sy9q48Jp/summary)Kobo survey for testing. 
- Configuration: See `openfn_kobo` in LP

**Destination: Postgresql** 
- I have requested a WCS db to use. 

## adaptor
Assume the destination database will be Postgres - use **language-postgresql**. 

## expression.js
[See original design notes](https://docs.google.com/document/d/1tuoef18h_r4T11GwWhmy-PD6SEKGJstyzf7Ir8Qzyao/edit#) for initial solution outline and questions.  In sum, we'll need the following jobs: 

**(1) Metadata sync (upserts tables and columns)**
1. **Job 1** creates tables and columns
2. **Job 2** (triggered by Job 1) creates/updates `N` jobs in OpenFn (/api/jobs/new)

**(2) Data sync (upserts records)**
3. **Job 3…N** pulls data for specific forms and upserts those data to Postgres

### (1) Metadata Integration
Job to automate the creation of the Postgres destination table based on Kobo xForm. 
1. Every X hrs, fetch form data from Kobo server to check for new or updated Kobo forms. 
2. Check whether a corresponding table already exists in the destination database. 
3. Create/update the database table accordingly. 

#### Metadata mapping rules: 
1. Destination database table should be named using `resource.name` (form name -i.e., "Rural Consumption"). 
2. Every destination table should have a `kobo_payload` JSONB column that captures the entire raw Message payload. 
3. Use Kobo question names to define the destination table column names. 
4. Any new Kobo questions added should trigger the creation of a new column. 
5. All repeat group data (determined by an array- i.e., `"group_scores":[...]"`) should be captured in another table with a foreign key relationship to the parent table. Therefore any survey with a repeat group will map to 2 tables, one parent and one child (i.e., `tbl_survey` and `tbl_survey_char`).

### (2) Data Integration
Jobs to automatically create and update the mappings from the Kobo form to the db table created in the above flow.

1. Run this job after the Metadata Integration flow completes to ensure all destination db tables have been created/ updated. This Job 2 (triggered by Job 1) creates/updates `N` jobs in OpenFn (/api/jobs/new).
2. The `N' jobs created should upsert the Kobo survey data in the db.

#### Data mapping rules: 
1. Use Kobo question names to map surveys to the relevant destination column.  
2. If a `uuid` is needed for upserting Kobo survey data, use `_id + _xform_id_string`. This will ensure uniqueness across Kobo servers if WCS is hoping to connect multiple accounts._ 
3. Map all repeat group questions to the child table created in job 1. 
4. Map the entire raw Message payload to the `kobo_payload` column created in job 1. 

## output.json

Fetching this [Kobo Rural Consumption survey](https://kf.kobotoolbox.org/#/forms/afCPRfan8JdBt9sy9q48Jp/summary) for the first time should:
1. Create 2 Postgres destination tables: the parent `tbl_wcs_rural_consumption_test` and child `tbl_wcs_rural_consumption_test_char` for capturing repeat group data
2. Create 1 job to map the Kobo survey data to the Postgres tables created

Assume OpenFn will fetch all Kobo survey forms and submissions on a cron-timer (i.e., every 3 hours). 

## Toggl
Please log your time to the [WCS - Automated Kobo-Postgres Sync](https://track.toggl.com/3335160/projects/163339135/team) project.

**Comment by taylordowns2000** [comment]
From Slack:
1. you fetch a form definition and it returns: {q1, q2, q3, etc.}
2. there are certain metadata fields which will be part of the form submission which are NOT in the definition above.
3. they will be found in EACH submission from Kobo, regardless of the form being used.
4. they include things like _id, _uuid, etc. (edited)

Taylor 3 minutes ago
(a) one might have {q1, q2, q3, more}
(b) and the other (the submission) might have {start, q1, q2, q3, _id, _version, more}
your job is to get a list of the things that appear in b but not a

Taylor 2 minutes ago
here's the data url: https://kf.kobotoolbox.org/api/v2/assets/afCPRfan8JdBt9sy9q48Jp/data/?format=json
to compare against the form url: https://kf.kobotoolbox.org/api/v2/assets/afCPRfan8JdBt9sy9q48Jp/

**Comment by lakhassane** [comment]
1.  We have notice that some forms do not have any questions (eg. `registration_form`). Should we discard those ? Is it normal ?
2. What should we do when a form name is `untitled`?
3. Forms may have multiple repeat groups. We have decided to name each child table with the following syntax: `${formName}_${groupName}`. Is this acceptable? What would the client like?
4. We have created a column on each table called `generated_uuid` and we have set its value with `state.data._id + state.data._xform_id_string`. **We are worried this will not work for repeat groups** but would like to test on a sandbox database on openfn.org to determine the best way forward.
5. We are unsure how every question type from kobo should match in Postgres but for now, we have offered the following mapping. 
```js
const mapType = {
        calculate: 'varchar',
        date: 'date',
        decimal: 'float4',
        end: 'date',
        integer: 'int4',
        select_one: 'varchar',
        start: 'date',
        text: 'text',
        today: 'date'
};
```
Each kobo question conforming to those types are considered as valid questions to insert in the database. If we encounter a question type that is not in that map, we will create a 'text' field to provide maximum flexibility. Is this acceptable?

## Sandbox testing request for WCS
We would next like to test this flow on OpenFn.org. Before we can do that, we need authorization from the client to test with a safe postgres instance, and authorization (or direction) on which OpenFn.org project space we should be autoconfiguring.

**Comment by aleksa-krolls** [comment]
@lakhassane _Great_ questions. Let's discuss today, especially `4. Repeat groups uuid`.
