### ISSUE TITLE
Add mappings for 1 table to BNS and NRGT jobs 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#46]
## Background
WCS is mapping data from BNS and NRGT surveys collected by its partners in different countries to one database for centralized reporting and monitoring. We implement 4 jobs for WCS and performed a large historical migration of thousands of BNS and NRGT survey submissions already - however, the client realized that 1 Postgres table was missing from the mapping specifications and wasn't updated in this historical migration. 

## The specific request. 

1. **Update** 4 existing jobs: 1. `bns/survey.js`, 2. `bns/price.js`, 3. `ngrt/2017.js`, 4. `ngrt/2019.js` to map to the new Postgres table `WCSPROGRAMS_KoboData`. 
In addition to current functionality, each job should also create 1 record in table `WCSPROGRAMS_KoboData` for every survey submission according to mapping specifications found here: https://docs.google.com/spreadsheets/d/1-8Wj97NFlv2sqp7CWQl1YGlFTApKkGYWRGOvgOv9m3Q/edit#gid=319757732

2. **Bulk Reprocess** already submitted forms to create 1 record for every survey submission in the Postgres table `WCSPROGRAMS_KoboData` according to mapping specifications found here. **I think Rita/Aleksa can do this on openfn.org.... but wanted to confirm given that submission volumes are 40k+** https://docs.google.com/spreadsheets/d/1-8Wj97NFlv2sqp7CWQl1YGlFTApKkGYWRGOvgOv9m3Q/edit#gid=319757732

## state.json
See LP for `WCS Central Database`. 

## adaptor
`language-postgres`

## expression
This change should be made in: 
1. `bns/survey.js`
2. `bns/price.js`
3. `ngrt/2017.js`
4. `ngrt/2019.js`

## output
For every Kobo form submitted, 1 new record created in `WCSPROGRAMS_KoboData` table

**Comment by aleksa-krolls** [comment]
@lakhassane please take this on after itau-social is done today.

**Comment by ritazagoni** [comment]
@lakhassane Please add two missing mappings to upserts to all 4 jobs (`bns/survey.js`, `bns/price.js`, `ngrt/2017.js`, `ngrt/2019.js`):
1. `WCSPROGRAMS_KoboData.DatasetOwner` (see mapping at https://docs.google.com/spreadsheets/d/1-8Wj97NFlv2sqp7CWQl1YGlFTApKkGYWRGOvgOv9m3Q/edit#gid=319757732&range=7:7)
2. `WCSPROGRAMS_KoboData.LastUpdateTime` (see mapping at https://docs.google.com/spreadsheets/d/1-8Wj97NFlv2sqp7CWQl1YGlFTApKkGYWRGOvgOv9m3Q/edit#gid=319757732&range=12:12)

**Comment by aleksa-krolls** [comment]
@lakhassane Amendment to Rita's comment above. Only quick change needed. Please add `WCSPROGRAMS_KoboData.LastUpdateTime` across the 4 jobs (see mapping at https://docs.google.com/spreadsheets/d/1-8Wj97NFlv2sqp7CWQl1YGlFTApKkGYWRGOvgOv9m3Q/edit#gid=319757732&range=12:12).
