### ISSUE TITLE
Setup `automation` jobs in prod to prepare for testing

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#49]
## Request
These `automation` jobs were created in response to this original [issue #7](https://github.com/OpenFn/wcs-consocsci/issues/7). Please (1) configure the `automation` jobs in the `WCS` OpenFn project on prod, and (2) connect the jobs to the following credentials...
1. Existing `openfn_kobo` credential `3118`: https://www.openfn.org/projects/1168/credentials/3118
2. Create a new Credential for the Postgres DB -  see LP for 'WCS ConSoSOc DB '). 

Please run a test on prod OpenFn.org using this `openfn_kobo` and the `WCS ConSoSOc DB` credentials. Double check that you've link the jobs to the correct credentials before running!! 

This is the same Kobo account you've been using to test locally, so I would expect this test on prod to behave the same as it does for you locally. If not, please keep me posted on what maybe needs to change.

**Comment by lakhassane** [comment]
@aleksa-krolls where can I find the LP `WCS ConSoSOc DB` credentials? I don't think it has been shared with me.

**Comment by aleksa-krolls** [comment]
@lakhassane I know the DB creds are a blocker, but how is this going? Can we get this all set up on OpenFn.org today? I want to make sure we're ready to test on prod as soon as we get these creds.

**Comment by lakhassane** [comment]
@aleksa-krolls yes it already configured. Just waiting for creds and `language-openfn` to get on prod. Otherwise I tested on staging also and it's working fine.
