### ISSUE TITLE
Hundreds of `BNS Survey` submissions fail because of gps validation

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#53]
## Bug? 
Several `BNS Survey` runs failed because of gps validation we added in [this commit](https://github.com/OpenFn/wcs/commit/d25e075649cd8f684304c44bc3032f47c54aea1b) @taylordowns2000 made. 
- See [run failure here](https://www.openfn.org/projects/1168/runs/10272789) with `"gps/lat": "699035"` and `"gps/long": "9739706"`. 
- [This ran](https://www.openfn.org/projects/1168/runs/9946961) successfully before ... is this only coming up because we made this commit after this first run? Is the validation we have in place correct? (I doubt there is a data entry issue across so many runs... I'm thinking we may need to change our validation.)

## state
WCS Central Database
[See this Message](https://www.openfn.org/projects/1168/messages/9824186) for example state.

## adaptor
`language-postgres`

## expression
https://github.com/OpenFn/wcs/blob/a7acd6797dffdaf5098c479e731da7b63f4be699/bns/survey.js#L35-L37

**Comment by taylordowns2000** [comment]
@aleksa-krolls , yes, that's right. It seems that we have two very different ways of reporting GPS, both are consdiered "BNS Survey". Can we find out from WCS how they expect GPS data to be delivered and how we should handle the various formats? In the first message below, for example, what does `"gps/lat": "699035"` mean? Currently, we throw an error to alert the administrator when values come in outside normal parameters, but we'll need to update our understanding of "normal"!

```js
// NOTE: This assumes all device-collected geo data follows specific lat, log data format
    if (cleanedSubmission.gps_method === 'device') {
      cleanedSubmission['gps/lat'] =
        cleanedSubmission.geo && cleanedSubmission.geo.split(' ')[0];
      cleanedSubmission['gps/long'] =
        cleanedSubmission.geo && cleanedSubmission.geo.split(' ')[1];
    } else if (
      Math.abs(parseFloat(cleanedSubmission['gps/lat'])) > 90 ||
      Math.abs(parseFloat(cleanedSubmission['gps/long'])) > 180
    ) {
      state.connection.close();
      throw `Invalid manual GPS entry: 'gps/lat': ${cleanedSubmission['gps/lat']}; 'gps/long': ${cleanedSubmission['gps/long']}`;
    }
```
In the second run, it seems they send data in this format:
```json
    "_geolocation": [
      -22.899558,
      43.416243
    ],
```
This should be a straightforward implementation, given clear requirements from WCS on the different ways that they report GPS locations.

1. https://www.openfn.org/projects/1168/messages/9539287
2. https://www.openfn.org/projects/1168/messages/9828199

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Confirmed with the client that if this validation check returns true, then they would like to _not_ upload any `gps` data to the DB. Please modify the following lines to not upload `gps` data (return a null value?) rather than throw an error and force the submission to fail.

https://github.com/OpenFn/wcs/blob/a7acd6797dffdaf5098c479e731da7b63f4be699/bns/survey.js#L31-L36
