### ISSUE TITLE
Bug: Columns for new questions not created by `AUTO2a. Sync to Postgres` if form is modified through the Kobo interface

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/wcs#55]
## Describe the issue
When (1) a new form is created or (2) a new question is added to a form through the Kobo interface, columns corresponding to the questions are not created by the job `AUTO2a. Sync to Postgres`.

## Expected behavior
When a new form is created through the Kobo interface, or a new question is added to an existing form through the interface, a new columns corresponding the questions are created. 

## Steps to Reproduce
Here is a link to a failed run on OpenFn.org which is indicative of the bug: 
1. Columns for newly created forms not added: https://www.openfn.org/projects/1168/runs/10303981. Run was triggered by https://www.openfn.org/projects/1168/runs/10303980.
2. Columns for questions added to existing form not added: https://www.openfn.org/projects/1168/runs/10303992. Run was triggered by https://www.openfn.org/projects/1168/runs/10303991.

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/wcs/blob/master/automation/02a-syncToPostgres.js

### state.json
Kobo: See LP for openfn_kobo
DB: See LP for WCS ConSoSci DB

## Steps to test the fix/resolve
Configuration on production only contains test data, it is safe to test. If new form or modification needed in Kobo, ping @ritazagoni.

**Comment by lakhassane** [comment]
@ritazagoni can we tomorrow try to replicate this bug together please?

**Comment by ritazagoni** [comment]
Issue was caused by Kobo not sending the `name` field for a question when it is created or modified through the web interface and  the question name is not manually modified. In this case only an autogenerated name is given to a question and sent in the `$autoname` field.

**Comment by aleksa-krolls** [comment]
@ritazagoni Should this be closed? Have we determined how to solve for such scenarios yet? 
(I find Github a good central place for us to manage outstanding questions to the client as well, so want to make sure nothing is dropped even if it is no longer a dev request.)

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 I'd like to discuss this one during our sync, because it sounds like WCS users frequently use the Kobo form builder web UI to modify forms. To summarize how I understand this issue...

[Kobo form definition](https://github.com/OpenFn/wcs/blob/master/sample_data/sample-form-definition.json) will typically provide us the following metadata details for different form questions... 
```
 {
        "name": "respondent_age",
        "type": "integer",
        "$kuid": "Q5zh55bQx",
        "label": ["Respondent's age"],
        "required": true,
        "$autoname": "respondent_age",
        "constraint": ". <= 100"
      }
```
However, it sounds like `name` is not provided if the Kobo question was added via the form builder. Only `$autoname`... is that correct @lakhassane? 

If so, I want to discuss implications of using `$autoname` (instead of `name` when not present) in order to define the needed Postgres column and OpenFn job mapping updates.

**Comment by aleksa-krolls** [comment]
@lakhassane As discussed, we will provide users more guidance for editing Kobo forms via the web UI. But to handle for scenarios where they add a new question and do _not_ specify a question `name`... please use `$autoname` as the default Postgres column name. 

@ritazagoni I think this will ensure we never miss an edited question, but let's do some in-depth testing on Monday.

**Comment by lakhassane** [comment]
Issue addressed by commit https://github.com/OpenFn/wcs/commit/13c9014db4822516926751e092c50e98e8bd9b3f
