### ISSUE TITLE
Output sql script in `automation` jobs and no longer auto-write to database

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#60]
## Background
WCS may sometimes want to _not_ execute the SQL immediately, so that there is time to adjust the sql script or even share with partners that might not have OpenFn access. Allowing DB admins to review the sql script ensures a layer of auditing before making any database changes. 

## Specific request
Currently the `automation` jobs automatically alter DB tables and create new OpenFn jobs. Rather than automatically updating DBs without any human review, can we introduce functionality that...

1. Outputs a SQL script that can be manually executed or adjusted? (Goal is to export and package these scripts for other users.) And... 
2. Would it possible to output this script in a way that could be run via OpenFn if the client did want to automate it as it is done currently? (i.e., output a `language-postgresql` job that can be turned "on" to run the sql script... similar to the `02b` job that writes jobs... this is _lower priority than 1_)

See step 3 in [this flow diagram](https://docs.google.com/presentation/d/1e9UPLnEIgtDPH6_dGqgQhUyZnc3TVl8ECSwJz5JgpNQ/edit#slide=id.ga632708288_0_36). Step `3a` should not be automated --> but rather output a sql script that admins can choose to review or execute. 

## state
This is a flow job, triggered by the `automation/01-getForms.js` job. 
Use `WCS ConSoSoc DB`! 

## expression
`automation/02a-syncToPostrges.js`

## adaptor 
`language-postgres` --> See [related pull](https://github.com/OpenFn/language-postgresql/pull/20)

## output
Running the job `automation/01-getForms.js` should have 2 outputs: 
1. Job `02a`: SQL script for altering DB tables that admins can adjust or execute
2. Job `02b`: OpenFn jobs that admins can adjust or turn "on" to auto-process

**Comment by aleksa-krolls** [comment]
@ritazagoni anything to add to this request?

**Comment by taylordowns2000** [comment]
desired API:
```
describeTable('x', { execute: false, writeSql });
createTable('x', { execute: false, writeSql });
insertMany('children', state => state.data.patients, { execute: false });
// insert into CHILD values ('taylor', gender: 'm')

insertMany('children', state => state.data.patients, { writeSql });
alterState(state => {
  console.log(
    `Completed ${state.queures.lenght} queries with code:`,
    JSON.stringify(state.queries, null, 2)
  );
  return state;
});

alterState(state => {
  console.log(
    'SQL for adminitrator execution:',
    JSON.stringify(state.queries, null, 2)
  );

  return state;
});
```

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 Confirmed that we want to offer the options to...
1. Write the sql script to the run logs (but do _not_ execute)
2. Write the sql script to the run logs AND execute automatically
We will give the admin controls over (1) whether to execute automatically and (2) whether prepared sql is saved to state (for additional security). 

Any other automation (e.g., sending sql script via email to the admin) will be a new feature request. Can you confirm my understanding here?

**Comment by lakhassane** [comment]
@taylordowns2000 your review is highly needed here: https://github.com/OpenFn/language-postgresql/pull/20

Basically I added `options` in `upsert()`. So I:
Check if `options` exist then `execute` and `writeSql` depending on the values.
If `options` is not given, we only `execute` but never `writeSql`.

If the PR is approved, then I can replicate on other helper ( `insertTable`, `modifyTable`, ...)

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 When merged, can you clarify what exactly the WCS admin needs to update in order to turn on/off the `options` for executing the sql automatically? 
@ritazagoni We'll need to note this as an admin step in the initial job setup, after users define which forms to use in this automation flow.

**Comment by lakhassane** [comment]
@aleksa-krolls here what needs to be updated by the admin would be `options` given as parameters.
The only way to prevent executing the sql automatically is to specify `{execute: false}`. Otherwise it is always executed. 
Also to log the sql in the state, they will always need to specify `{writeSql: true}` (or `false` to ignore).
e.g:
`insertTable('user', {writeSql: true, execute: false})` => will log and not execute
`insertTable('user')` => will execute and not log

**Comment by aleksa-krolls** [comment]
@lakhassane I see `writeSql` referenced multiple times in the job. Would I specify `{writeSql: true, execute: false}` everywhere I see `writeSql`? Or only on L17?
Can you please add in-line comments where the admin _should_ update the `options`?

**Comment by lakhassane** [comment]
@aleksa-krolls you will need to specifiy it in every helper function call if you write to log the sql on state. 
Im adding comments on the job.

**Comment by aleksa-krolls** [comment]
@lakhassane Thank you. When comments added, feel free to close the job.
