### ISSUE TITLE
Handle additional Kobo data types

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#61]
## Background
Currently we're handling for the following Kobo question data types... but there are more we are currently not accounting for. 
https://github.com/OpenFn/wcs/blob/47d4abfff3d6d4f026e94e270c0eb81dce70ff68/automation/01-getForms.js#L40-L51

## Specific request
We are currently handling for data types #1-10 in the list below, but we need to ensure the automation can...
1. Handle unicode to save other non-English languages - so should we use `nvarchar` instead of `varchar`? (Please advise on what other changes might apply here)
2. Supports the full list of data types below

### Kobo data types
1. `calculate: 'varchar'` --> change to `nvarchar`?
2. `date: 'date'`
3. `decimal: 'float4'` --> what default precision is set here? We need to handle a wide value range (e.g., `10000000000001`, `1.0000000000001`, `-1.0000000000001`)
4. `end: 'date'` --> does this capture time? or is there a `datettime` column type? 
5.  `integer: 'int4'`
6. `select_one: 'varchar'` --> change to `nvarchar`?
7.  `start: 'date'`  --> does this capture time? or is there a `datettime` column type? 
8. `text: 'text'`
9. `today: 'date'`
10. `jsonb: 'jsonb'`
11. `select_multiple: 'text'`
12. `geopoint:  'text'`

## state
Use `WCS ConSocSci DB` and the `openfn_kobo` account

## expression
`automation/01-getForms.js`

## adaptor
`language-http`

## output
DB columns should be configured to handle a wider range of data types and value ranges.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane Santosh confirmed that Postgres `varchar` columns can handle unicode, so let's use that column data type. 
Also WCS added a new Kobo form... when testing, Job `2a` failed I think related to the `nvarchar` data type. [See run failure](https://www.openfn.org/projects/1168/runs/10367451) where I see `error: type "nvarchar" does not exist`. 

Please make sure this automation is working for this new form `EuSwmSiteSurvey`. 
Here's the Kobo project link: https://kf.kobotoolbox.org/#/forms/afCP2i7HmbueECdhgozGwZ/landing

**Comment by taylordowns2000** [comment]
This all makes sense. AK, you were right in pointing out (in Slack) that
`nvarchar` is only for MSSQL. This run used the postgres adaptor and is
querying a postgres database.

**Comment by lakhassane** [comment]
@aleksa-krolls @taylordowns2000 can this be closed? I am just trying to clean here to see what is remaining properly.

**Comment by lakhassane** [comment]
I have just confirmed with @taylordowns2000. Closing this issue.
