### ISSUE TITLE
Add prefixes to DB table names and use camelCase across `automation` postgres jobs

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#62]
## Request
To support naming convention standards, WCS has requested that we...
1. Use Upper `CamelCase` in all naming conventions for any Postgres tables or columns in the `automation` jobs. 
2. Introduce two prefixes for all Postgres table names (this does _not_ apply to columns). Prefix1 should have the default value `WCS` and prefix2 the default value `FormGroup`... but both may be adjusted by the admins depending on the database and project they are connecting with. DB tables should follow the naming convention `${Prefix1}__{Prefix2}__TableName` (e.g., `WCS__FormGroup__BnsSurvey2020`). 

## state
Use the `openfn_kobo` acct and `WCS ConSoSci` database. 

## expression
I think these changes need to be applied in `automation/01-getForms.js` where we specify the DB changes to be made based on the fetched forms. 
https://github.com/OpenFn/wcs/blob/master/automation/01-getForms.js#L161-L164

## adaptor
`language-http`

## output
Example postgres table names: `WCS__FormGroup__KoboBnsAnswer` or `TNC__FormGroup__RuralConsumptionNdoki`.

**Comment by aleksa-krolls** [comment]
@ritazagoni anything add to this one as well?

**Comment by taylordowns2000** [comment]
Verified output, closing

**Comment by aleksa-krolls** [comment]
I see the default prefix string `'WCS__FormGroup_'`referenced in multiple places in the `01-getForms.js` job. I would like there to be _one_ place where this prefix is defined so that if the client modifies the prefix name, it will be applied throughout the automation. 
https://github.com/OpenFn/wcs/blob/master/automation/01-getForms.js#L138
https://github.com/OpenFn/wcs/blob/master/automation/01-getForms.js#L156
