### ISSUE TITLE
How should questions that start with numerics be converted to postgres columns?

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#65]

**Comment by lakhassane** [comment]
@taylordowns2000 I had to address this issue with a temporary solution otherwise testing table creation was impossible.
We will need confirmation from the client @aleksa-krolls 

For now, if a question starts with a numeric value (e.g. `_3rd_sp_sold2`), we camelize it (which turns it into `3rdSpSold2`) and then add back the `_` otherwise it won't pass on `postgres`. So final output would be `_3rdSpSold2`

**Comment by aleksa-krolls** [comment]
@ritazagoni I forget, do we want to camel-ize _columns_? Or only DB tables? (Maybe another WCS question?)

**Comment by taylordowns2000** [comment]
Also, I see we're going with Pascal here... just wanted to make sure that's
the client's desire:

"Camel case is often used as a naming convention
<https://en.wikipedia.org/wiki/Naming_convention_(programming)> in computer
programming, but is an ambiguous definition due to the optional
capitalization <https://en.wikipedia.org/wiki/Capitalization> of the first
letter. Some programming styles prefer camel case with the first letter
capitalised, others not.[1]
<https://en.wikipedia.org/wiki/Camel_case#cite_note-1>[2]
<https://en.wikipedia.org/wiki/Camel_case#cite_note-nfrmwk-2>[3]
<https://en.wikipedia.org/wiki/Camel_case#cite_note-3> For clarity, this
article calls the two alternatives *upper camel case* (initial uppercase
letter, also known as *Pascal case*) and *lower camel case* (initial
lowercase letter, also known as *dromedary case*). Some people and
organizations, notably Microsoft <https://en.wikipedia.org/wiki/Microsoft>,
[2] <https://en.wikipedia.org/wiki/Camel_case#cite_note-nfrmwk-2> use the
term *camel case* only for lower camel case. *Pascal case* means only upper
camel case." - wiki

**Comment by aleksa-krolls** [comment]
@taylordowns2000 we should put back the `_` so the output is `_3rdSpSold2`. So that's what we have in place, yes? And if I get client sign-off on Pascal case, we're `GoodToGo` and I can close this issue, yes?
