### ISSUE TITLE
Job `01-getForms.js` state too big

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#67]
I received another OpenFn notification this morning when fetching only 1 updated form. [See run here](https://www.openfn.org/projects/1168/runs/10367450). 

We discussed posting the final state of job `01` back to the OpenFn Inbox... then configuring the `2a` and `2b` jobs to run on message filter triggers. 

I also think this approach would improve error handling and re-processing, because it's not possible to easily re-run any of the `2` jobs without re-fetching from Kobo. Ideally I could simply click to re-try [this run failure](https://www.openfn.org/projects/1168/runs/10367451) when the job issues are resolved. Can we discuss this in our sync?

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 as discussed --> we're introducing a job `00` to only fetch the newly updated Kobo forms --> and then to triggers jobs `01` and `02` to process this data.

**Comment by taylordowns2000** [comment]
Closed with introduction of `00`.
