### ISSUE TITLE
Update field conversion for `WCSPROGRAMS_KoboBnsAnswerhhmembers` table `Birth` column

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/wcs#71]
## Current behavior

In the `WCSPROGRAMS_KoboBnsAnswerhhmembers` table the `Birth` column expects an `integer` value. When we receive a `date` string (e.g. `1992-01-01`) writing to the DB fails. Example failed run: https://www.openfn.org/projects/1168/runs/10457027

## Request
Keep `integer` as default expected value for `WCSPROGRAMS_KoboBnsAnswerhhmembers` table `Birth` column. 
However, if a date string is received instead, parse the first 4 digits and write that to DB. 

## state
See LP for `WCS Central Database`. **Test with a real-message to ensure that you will only upsert records and not create any new dummy surveys** 

Use [this message](https://www.openfn.org/projects/1168/messages/10056401) linked to the failed run to test & verify the change.

## adaptor
`language-mssql`

## output
For example: 
1. `1992` should output as `1992`
2. `1991-01-01` should output as `1991`

**Comment by aleksa-krolls** [comment]
@ritazagoni bc we have so many wcs workstreams going on, very important to specify credentials and adaptor. Please provide a specific example and assign to Mamadou when ready. Thanks!

**Comment by ritazagoni** [comment]
Clear!

**Comment by aleksa-krolls** [comment]
@lakhassane when done please let @ritazagoni know when ready for testing. 

Rita, we'll want to re-run all the failed BNS runs in bulk and let Diane know once testing passes.

**Comment by lakhassane** [comment]
@ritazagoni Im unable to test due to `IP` restrictions. If it's safe to merge on master (cc @aleksa-krolls ) give it a try and let me know please.

**Comment by aleksa-krolls** [comment]
@lakhassane You can merge and test on prod. Re-run this message: https://www.openfn.org/projects/1168/runs/10457027

**Comment by lakhassane** [comment]
Run successfull

**Comment by ritazagoni** [comment]
@lakhassane In some cases the runs fail, see run https://www.openfn.org/projects/1168/runs/10478882 on message https://www.openfn.org/projects/1168/messages/10081776. Seems like the issue is when we have no `birth_head` in state so we try to parse `undefined`.

**Comment by lakhassane** [comment]
@ritazagoni correction made. I rerun the job and having green check

**Comment by aleksa-krolls** [comment]
@ritazagoni Seems to be working, so can you please bulk re-try all BNS Messages "in a failed state" to confirm no other issues? (See OpenFn docs: https://docs.openfn.org/documentation.html#bulk-reprocess-messages).

If resolved, please close this issue. If there are still issues - please move this to the Backlog. Thanks!
