### ISSUE TITLE
Set UNIQUE constraint on `GeneratedUuid` or `DatasetID` when CREATEing or ALTERing tables

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#74]
![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/9bdeb103-fdb1-4441-9633-035457a68d4c)

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/d802daf0-a1e8-4ed9-a1a3-71f00e688492)

**Comment by aleksa-krolls** [comment]
@lakhassane friendly reminder to ping whenever stuff is ready to review - thanks! :)

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 Confirming this is related to the pending pull request? This is in Ready to Review column, but looks like this error is still present: `error: there is no unique or exclusion constraint matching the ON CONFLICT specification`
https://www.openfn.org/projects/1168/runs/10542994

**Comment by taylordowns2000** [comment]
Yes, this is the focus of Mamadou's open PRs on WCS and the Postgres
adaptor.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , just realised that you were not tagged on this when I put it in review/QA yesterday. Apologies.
