### ISSUE TITLE
Manual cursor not updating in `03-KOBO-AUTO-Get Kobo Data` job

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/wcs#81]
## Describe the bug
Manual cursor doesn't update after a fetch from Kobo in `03-KOBO-AUTO-Get Kobo Data` job. Same issue as fixed in https://openfn.org/projects/1168/jobs/3737.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://openfn.org/projects/1168/runs/10589020

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/wcs/blob/master/automation/03-getKoboData.js

### state.json

Either provide state directly, or link to a file. If sensitive information
should be in state, redact it and provide instructions for where it can be
found.

```json
{
  "configuration": ["SEE LAST PASS: 'OpenFn Kobo Toolbox'"],
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```
## Expected behavior
Manual cursor updated to timestamp of latest fetch at the end of the run.

## To test/resolve
1. After the desired output is working locally (from the CLI), please push commits to master.
2. Please test the change on OpenFn.org by re-running this [run](https://openfn.org/projects/1168/runs/10589020) and confirming success.

**Comment by taylordowns2000** [comment]
@ritazagoni , think this is all set.

Before the change: https://openfn.org/projects/1168/runs/10596572
After the change: https://openfn.org/projects/1168/runs/10597026
