### ISSUE TITLE
Auto-sync fails for form with nested groups

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#84]
## Describe the bug
Here is a Kobo form with nested groups: Kobo form definition: https://kf.kobotoolbox.org/api/v2/assets/atFB5uoXJtzwJoPCKtNPjg/?format=json

1. `02a` Sync to postgres fails for form with nested groups. I wonder if this error is due to the length of the form name? Or because a similar form has been synced? 
Run failure: https://www.openfn.org/projects/1168/runs/10596816
Here is the `00` run that auto-generate the job: https://www.openfn.org/projects/1168/runs/10596814

Update:
`02a Sync to Postgres` succeeded with same form with shorter name: https://openfn.org/projects/1168/runs/10597271
Form definition: https://kf.kobotoolbox.org/api/v2/assets/ammbPRCFv4sF9UFxDMifnq/?format=json

2. Also it looks like the auto-generated job created via `02b` has syntax errors: https://www.openfn.org/projects/1168/jobs/3777

## To Reproduce
1. Run job `00` with: `{ uid: 'atFB5uoXJtzwJoPCKtNPjg', p1: 'WCS', p2: '4levelrepeat'} `
https://www.openfn.org/projects/1168/runs/10596814
2. This will trigger job `02a` and `02b`

### expression.js
Related to jobs `02a` and `02b`

### state.json
Kobo: `openfn_kobo`
DB: `WCS ConSoSci`

## To test/resolve
See `To Reproduce` steps.

**Comment by lakhassane** [comment]
RE 1.I wonder if this error is due to the length of the form name? Or because a similar form has been synced?

Yes @aleksa-krolls this is because of the length. In this case, even after trimming with repeat group name, the length is still above 63 characters. Then postgres try again to reduce to 63. So it won't be inserted since there is already a reduced (by postgres) table with the same name.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , @ritazagoni : does WCS want us to design some patterns for form naming or do they want to advise here? We could spend as much or as little time as they'd like coming up with different naming conventions and then walk them through the relative merits/drawbacks of the conventions. They could also (on paper) decide how they'd like to name these tables given the constraints we know:

1. 63 characters or fewer
2. they want repeat groups to have their own tables
3. repeat groups might have the same name as other repeat groups, so (for the time being) we've implemented the recursive  `parentTableName-repeatGroupName` convention.
