### ISSUE TITLE
Filter 'bns_matrix' questions by substring

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#88]
## Background
Sometimes Kobo questions for bns matrix questions will be labeled as `bns_matrix/questionName` and sometimes there will be additional text in the metadata names - e.g., `hh_assets/bns_matrix/questionName`. 

## Request
L68: Change from `startswith` to `includes` to search for any questions that contain the substring `'bns_matrix'`
L69: Remove this search filter all together... not all these questions will end with `'possess'`
https://github.com/OpenFn/wcs/blob/f60d64a5ccd53c4d596503afbaa41a824c00c851/bns/survey.js#L68-L69

## State
You can test on prod here: https://www.openfn.org/projects/1168/messages/10284985
All the Kobo fields starting with `hh_assets/bns_matrix...` should map to the table `WCSPROGRAMS_KoboBnsAnswerGS`

**Comment by taylordowns2000** [comment]
@lakhassane made the change. I've tested it here:

BEFORE: https://www.openfn.org/projects/1168/runs/10762035
AFTER: https://www.openfn.org/projects/1168/runs/10823389

**Comment by dianedetoeuf** [comment]
Hi all, 

Hi, 

This is great thank you! Can I re-run the historical kobo data for this Uganda form?

Best
—

Diane Detoeuf
Poultry production and livelihoods diversification, Northern Congo
Chief of Party to USAID/DRC
Wildlife Conservation Society - Congo Programme

151 Avenue du Général de Gaulle, Brazzaville, Congo
Tel: +242 05 358 48 80
Skype: diane.detoeuf

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane We need to make one more change to ensure the values map correctly. See how mappings are null in row 23 of [run log](https://www.openfn.org/projects/1168/runs/10823389).

On L70, the job currently expects the `'bns_matrix'` substring will be always in the same position, however this could change. 
https://github.com/OpenFn/wcs/blob/master/bns/survey.js#L70

We need to update this logic so that mappings on L75-79 come through correctly. These fields might need to map from different versions of state - examples where we need to start mapping after the `'bns_matrix_'`substring...
`bns_matrix_truck_car/bns_matrix_truck_car_possess`
`hh_assets/bns_matrix_truck_car/bns_matrix_truck_car_possess`
`groupOtherName/bns_matrix_truck_car/bns_matrix_truck_car_possess`
